__OUTLINE__
1. introduction to numpy
2. array basics
3. array vs list
4. dot product
5. speed test array vs list
6. multidimentiional arrays (nd-array)
7. array indexing/slicing/booleaan indexing
8. reshape
9. concatenation
10. broadcasting
11. (data science) function and axes
12. daatatypes
13. copying
14. generating arrays
15. random numbers
16. linear algebra (np.linalg)
- eigenvalues
- solving linear system
17. loading data from csv

__NUMPY__
- Numpy is core library for scientific computing in python
- data science, machine learning, deep learning
- scikit-learn, matplotlib, pandas

- __High Performaance__ multidimentional array => __fast__
- mathematical operations with arrays
- a lot of code written in C

__NUMPY USECASES__
- Array/Matrix operation - linear algebraa
- dot product
- matrix multiplications
- inverse, determinant
- eigenvectors
- random numbers
- working with imaages represented as array

In [2]:
import numpy as np

print(np.__version__)

a  =np.array([1,2,3])
print(f"the array of 'a' is: {a}")
print(f"the shape of 'a' is: {a.shape}")
print(f"the data type of 'a' is: {a.dtype}")
print(f"the number of dimention in 'a' is: {a.ndim}")
print(f"the size of 'a' is: {a.size}")
print(f"the size of an item in 'a' is: {a.itemsize}")

1.26.4
the array of 'a' is: [1 2 3]
the shape of 'a' is: (3,)
the data type of 'a' is: int32
the number of dimention in 'a' is: 1
the size of 'a' is: 3
the size of an item in 'a' is: 4


In [3]:
# mathematical operation of numpy
b = a * np.array([2,2,3])
print(b)

[2 4 9]


In [4]:
c =  a + np.array([4,4,4])
print(c)

[5 6 7]


In [5]:
a = a * 3
print(a)

[3 6 9]


In [6]:
a = np.sqrt(a)
print(a)

[1.73205081 2.44948974 3.        ]


In [7]:
c = np.sqrt(c)
print(c)

[2.23606798 2.44948974 2.64575131]


In [8]:
# dot product: is the sum of product of corresponding entries
l1 = [1,2,3]
l2 = [4,5,6]
a1 = np.array([l1])
a2 = np.array([l2])

# product
dot = 0
for i in range(len(l1)):
    dot += l1[i] * l2[i]
print(dot)

32


In [ ]:
dot = a1 + a2 